name: "hash-checker"
repository: github.com/kkaftan/trivy-hash
version: "0.7.0"
usage: scan for checksum check
description: |-
  A Trivy plugin that scans the images and check if checksum equal
  Usage: trivy hash-checker -i image_name [command options]
  OPTION: Atleast 1 required
  -d  Datenbank, in dem sich vertrauliche Dateien / Malwares befinden und deren Hashsumme;
  Datenbank benötigt Spalte: Hashsummen
  -t  Analog zur Datenbank, kann eine Textfile mitgegeben werden;
  Struktur der Textfile muss wie folgs aussehen: Hashsummen, Pfad / Name, Klassifizierungsstufe
platforms:
  - selector: # optional
      os: darwin
      arch: amd64
    uri: ./trivy-hash # where the execution file is (local file, http, git, etc.)
    bin: ./trivy-hash # path to the execution file
  - selector: # optional
      os: linux
      arch: amd64
    uri: ./trivy-hash
    bin: ./trivy-hash
